steps:
  build:
    when:
      event: [push, pull_request]
    image: alpine
    commands:
      - apk update
      - apk add ncurses-dev gcc libc-dev flex bison linux-headers make git python3
      - rm include/macromagic.h
      - make
      - make install
